### ISSUE TITLE
Errors in mt32emu 2.5.0

### ISSUE THREAD

**Issue by IlyaIndigo** [munt/munt#54] opened 2021-04-05 08:39 UTC
I apologize in advance if my style of presentation seems rude and tactless. I have a poor grasp of spoken English and express myself in the language of technical documentation.

0 Project self-identification. munt or mt32emu?
You originally named the project munt, but the library and executable are called libmt32emu and mt32emu-qt respectively.
I thought you called the project munt before, then changed your mind and wanted to call it mt32emu. The decision is very correct in my opinion.
But you release both munt 2.4.0 and mt32emu 2.5.0 simultaneously with almost the same content.
What is this and how do I understand it?

1 ChangeLog mt32emu-qt
```
HEAD:
* Fixed the ROM scanner function that didn't filter out partial ROMs which aren't yet supported. Related to (#44).
```
Is this fixed in mt32emu 2.5.0 or not?

2 You added the pakageconfig file which is great, but you missed at least 2 gross errors.
2.1 The resulting mt32emu.pc file when built in openSUSE Tumbleweed x86_64 is
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}//usr/lib64
includedir=${prefix}/include

Name: libmt32emu
Description: C/C++ library to emulate (approximately) the Roland MT-32, CM-32L and LAPC-I synthesiser modules
URL: http://munt.sourceforge.net/
Version: 2.5.0
Requires.private: 
Libs: -L${libdir} -lmt32emu
Cflags: -I${includedir}
```
2.1.1 Obviously, the 3rd line should be.
`libdir=/usr/lib64`
But something, most likely in the sed script, went wrong.
2.1.2 The URL is not needed in this file at all. I haven't seen other open source projects post URLs here.
But if you think that it is still needed, then let it link not to http riderect 80, but to the https address of the project on github.
2.2 After the `%cmake_install` macro, the mt32emu.pc file is installed in `%{_prefix}/lib/pkgconfig/%{name}.pc` (`/usr/lib/pkgconfig/mt32emu.pc`) instead of `%{_libdir}/pkgconfig` (`/usr/lib64/pkgconfig/mt32emu.pc`).
There must be an error in the installation script.

3 You added a desktop-file for mt32emu-qt which is great, but at least the category is wrong.
https://build.opensuse.org/package/view_file/multimedia:libs/mt32emu/mt32emu.desktop?expand=1
It should be `Categories=Qt;AudioVideo;Midi;`
It's also not clear why they even mention munt if it's mt32emu... but that comes from point 0.

4 You added an icon for the desktop-file that's great too, but there's nothing wrong with it either.
4.1 This is a primitive 256x256 png icon.
Why do you need such a big size, and it's the only size you need, for such a primitive monochrome icon?
Linux does this in 2 ways.
- It is broken into smaller ones in `/usr/share/icons/hicolor/NxN/apps/mt32emu.png`, where N necessarily contains 16, 32, 64, and optionally 128 and 256.
But in this case, I don't understand what the dimensions of 128 and 256 are for such a primitive monochrome icon?
- If you're too lazy to break into multiple files, create a vector svg or svgz icon and put it here `/usr/share/icons/hicolor/scalable/apps/mt32emu-qt.svgz` Then the icon in the maximum possible quality and it does not need to break into smaller.

In general you need to do something from this, if you choose the 1st option, I recommend to limit the size 64. Well, a maximum of 128, I do not even know why.

**Comment by sergm** [comment] 2021-04-05 10:11
> 0 Project self-identification. munt or mt32emu?

The project is named munt. As README says, it comprises of several subprojects, mt32emu is one of them. mt32emu implements the emulation core as a library and it is used in almost all the other subprojects of munt. I think this situation is due to historical reasons, but I'm fine with this so far.

> But you release both munt 2.4.0 and mt32emu 2.5.0 simultaneously with almost the same content.
> What is this and how do I understand it?

We have released mt32emu 2.5.0 (the library) with some important new features. When we add necessary support to the other respective subprojects, we'll roll out them as well. Finally, the entire munt package will be released, which is a convenient form of distribution on other platforms, e.g. Windows.

> 1 ChangeLog mt32emu-qt
> 
> ```
> HEAD:
> * Fixed the ROM scanner function that didn't filter out partial ROMs which aren't yet supported. Related to (#44).
> ```
> 
> Is this fixed in mt32emu 2.5.0 or not?

This is fixed in the HEAD version of mt32emu-qt, so that this application is now compatible with the library version mt32emu 2.5.0. Previously, mt32emu-qt implemented the ROM scanner in an assumption that partial ROMs do not exist, despite the relevant library API suggested otherwise. This bug doesn't seem critical, so we are not bumping version mt32emu-qt 1.8.1 to deliver the fix urgently. If this is important to deliver for openSUSE, please let me know, and we'll make a bugfix release of mt32emu-qt.

> 2 You added the pakageconfig file which is great, but you missed at least 2 gross errors.

Please note, that the pkg-config file is generated by the cmake build script. This means that some configuration variables are transferred from the cmake build system. In particular, the contents of variables `LIB_INSTALL_DIR` and `libmt32emu_PKGCONFIG_INSTALL_PREFIX` affect the data populated into the generated mt32emu.pc file and its location.

> 2.1 The resulting mt32emu.pc file when built in openSUSE Tumbleweed x86_64 is
...
> libdir=${exec_prefix}//usr/lib64
...
> URL: http://munt.sourceforge.net/
...
> 2.1.1 Obviously, the 3rd line should be.
> `libdir=/usr/lib64`
> But something, most likely in the sed script, went wrong.

The cmake formula is `libdir=${exec_prefix}/@LIB_INSTALL_DIR@`, so evidently, the variable `LIB_INSTALL_DIR` needs an adjustment. For openSUSE, I'd recommend to use the same value I'm using for building `x86_64` Fedora packages: `lib64`.

> 2.1.2 The URL is not needed in this file at all. I haven't seen other open source projects post URLs here.

Would you be so kind and point me to where this is specified? When adding the URL field, I was referring to the [pkg-config-guide](https://people.freedesktop.org/~dbn/pkg-config-guide.html) that suggested to fill it in.

> But if you think that it is still needed, then let it link not to http riderect 80, but to the https address of the project on github.

+1 for HTTPS, I'll update the project URL. Note however, the SourceForge remains the primary project host, GitHub is used for easier collaboration.

> 2.2 After the `%cmake_install` macro, the mt32emu.pc file is installed in `%{_prefix}/lib/pkgconfig/%{name}.pc` (`/usr/lib/pkgconfig/mt32emu.pc`) instead of `%{_libdir}/pkgconfig` (`/usr/lib64/pkgconfig/mt32emu.pc`).
> There must be an error in the installation script.

Unfortunately, the location of pkg-config files in each system varies, hence we have to resort to make the directory, where to install mt32emu.pc file to, configurable. By adjusting the `libmt32emu_PKGCONFIG_INSTALL_PREFIX` variable, the location of mt32emu.pc file can be changed to fulfil requirements of any particular distribution.

> 3 You added a desktop-file for mt32emu-qt which is great, but at least the category is wrong.
> https://build.opensuse.org/package/view_file/multimedia:libs/mt32emu/mt32emu.desktop?expand=1
> It should be `Categories=Qt;AudioVideo;Midi;`

Agree, the category needs to be improved. However, filename 'mt32emu.desktop' is wrong, as the mt32emu library has no user interface.

> 4 You added an icon for the desktop-file that's great too, but there's nothing wrong with it either.
> 4.1 This is a primitive 256x256 png icon.
> Why do you need such a big size, and it's the only size you need, for such a primitive monochrome icon?

Sadly, we haven't obtained a scalable icon, which would be my preference to use as a desktop icon. The icon came with a set of bitmap images of variable resolutions. As a first step, we added the high-resolution icon because it can be downscaled without significant degrade in quality, in contrast to adding a lower resolution icon only. I'm going to add all the available icons for more resolutions to configure GNU desktops better.

**Comment by IlyaIndigo** [comment] 2021-04-05 11:53
`-Dlibmt32emu_PKGCONFIG_INSTALL_PREFIX="%{_libdir}"` 
Solved the installation problem, but not the content.

> The cmake formula is `libdir=${exec_prefix}/@LIB_INSTALL_DIR@`, so evidently, the variable `LIB_INSTALL_DIR` needs an adjustment. For openSUSE, I'd recommend to use the same value I'm using for building `x86_64` Fedora packages: `lib64`.

LIB_INSTALL_DIR=%{_libdir} (/usr/lib64 for x86_64), by default, but instead of `libdir=/usr/lib64` I get `libdir=${exec_prefix}//usr/lib64`.
I have to use sed.

**Comment by sergm** [comment] 2021-04-05 12:17
By design, LIB_INSTALL_DIR should contain _Relative installation path to libraries_ under the installation prefix. The latter can be configured, and most probably already is system-wide, to contain an absolute path, e.g. "/usr", with the CMAKE_INSTALL_PREFIX variable.

**Comment by IlyaIndigo** [comment] 2021-04-05 12:51
Thank you very much, I have figured out cmake. :-)
```
%cmake -LA \
       -DCMAKE_SHARED_LINKER_FLAGS="-lm" \
       -DLIB_INSTALL_DIR:PATH="%{_lib}" \
       -Dlibmt32emu_PKGCONFIG_INSTALL_PREFIX="%{_libdir}"
```

**Comment by sergm** [comment] 2021-04-05 13:05
You welcome.
On a side note, I wish there were more similarities among all the GNU distributions, then packaging would be simpler 🙁

**Closed** 2021-04-05 13:09 UTC
Labels: Support, libmt32emu, mt32emu-qt
